name: Windows build

on:
  workflow_call:

permissions:
  contents: read

# env: 
#   PATH: C:\opensourcecobol4j\bin;C:\ocesql4j\bin
#   CLASSPATH: C:\opensourcecobol4j\lib\libcobj.jar;C:\ocesql4j\ocesql4j.jar
#   #COBOL4J_LIBCOBJ_JAR_PATH: C:\opensourcecobol4j\lib\libcobj.jar
#   OCESQL4J_OCESQL4J_JAR_PATH: C:\ocesql4j\lib\ocesql4j.jar

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0
        
    - name: Install Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Install postgresql
      uses: ikalnytskyi/action-setup-postgres@v6
      with:
        username: user
        password: user
        database: testdb
        port: 5432
      #  id: postgres

    - name: Checkout opensource COBOL 4J
      uses: actions/checkout@v4
      with:
        repository: opensourcecobol/opensourcecobol4j
        path: opensourcecobol4j

    - name: Restore NuGet packages of opensourcecobol4j
      run: nuget restore ./opensourcecobol4j/win/
    
    - name: Install opensource COBOL 4J
      run: |
        cd opensourcecobol4j/libcobj
        ./gradlew shadowJar
        mkdir C:\opensourcecobol4j\lib
        copy app/build/libs/libcobj.jar C:\opensourcecobol4j\lib
        cd ../
        msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:./cobj/:./win:./lib win/opensourcecobol4j.sln
        mkdir C:\opensourcecobol4j\bin
        mkdir C:\opensourcecobol4j\config
        copy win/x64/Release/cobj.exe C:\opensourcecobol4j\bin\
        copy config/*.conf C:\opensourcecobol4j\config\

    - name: Install Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Build ocesql4j.jar
      run: |
        cd dblibj
        copy ../opensourcecobol4j/libcobj/app/build/libs/libcobj.jar lib
        sbt assembly
    
    - name: Restore NuGet packages of ocesql4j
      run: nuget restore ./win/

    - name: Build ocesql.exe
      run: |
        msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:ocesql win/ocesql.sln
    
    # - name: Version display
    #   run: |
    #     cd win
    #     ./install.ps1
    #     $env:PATH=";C:\ocesql4j\bin"
    #     $env:CLASSPATH="C:\ocesql4j\ocesql4j.jar;"
    #     ocesql --version

    # - name: Create psql user
    #   run: |
    #     createuser -d -U postgres -P user
    #     createdb  testdb --owner=user
    #    psql -c "ALTER USER myuser WITH PASSWORD 'mypassword'"
    
    - name: Test SQL connection
      run: |
        cd win
        ./install.ps1
        $env:PATH+=";C:\opensourcecobol4j\bin;C:\ocesql4j\bin;C:\ocesql4j\config"
        $env:CLASSPATH="C:\opensourcecobol4j\lib\libcobj.jar;C:\ocesql4j\ocesql4j.jar"
        cd ../sample
        copy ../copy/sqlca.cbl .
        ocesql FETCHTBL.cbl  FETCHTBL.cob
        ocesql INSERTTBL.cbl INSERTTBL.cob
        cobj INSERTTBL.cob
        cobj FETCHTBL.cob
        dir
        java INSERTTBL
        java FETCHTBL