name: Windows build

on:
  workflow_call:

permissions:
  contents: read

env: 
  PATH: C:\opensourcecobol4j\bin;C:\ocesql4j\bin
  CLASSPATH: C:\opensourcecobol4j\lib\libcobj.jar;C:\ocesql4j\ocesql4j.jar
  #COBOL4J_LIBCOBJ_JAR_PATH: C:\opensourcecobol4j\lib\libcobj.jar
  OCESQL4J_OCESQL4J_JAR_PATH: C:\ocesql4j\lib\ocesql4j.jar

jobs:
  test:
    runs-on: windows-latest

    services:
      postgres15:
      image: postgres:15
      ports: 
        - 5433:5432
      env:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: main_user
        POSTGRES_DB: testdb
        POSTGRES_HOST_AUTH_METHOD: 'trust'
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0
        
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Checkout opensource COBOL 4J
      uses: actions/checkout@v4
      with:
        repository: opensourcecobol/opensourcecobol4j
        path: opensourcecobol4j

    - name: Restore NuGet packages of opensourcecobol4j
      run: nuget restore ./opensourcecobol4j/win/
    
    - name: Install opensource COBOL 4J
      run: |
        cd opensourcecobol4j/libcobj
        ./gradlew shadowJar
        mkdir C:\opensourcecobol4j\lib
        copy app/build/libs/libcobj.jar C:\opensourcecobol4j\lib
        cd ../
        msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:./cobj/:./win:./lib win/opensourcecobol4j.sln
        mkdir C:\opensourcecobol4j\bin
        copy win/x64/Release/cobj.exe C:\opensourcecobol4j\bin\
    
    - name: Build ocesql4j.jar
      run: |
        cd dblibj
        copy ../opensourcecobol4j/libcobj/app/build/libs/libcobj.jar lib
        sbt assembly
    
    - name: Restore NuGet packages of ocesql4j
      run: nuget restore ./win/

    - name: Build ocesql.exe
      run: |
        msbuild /p:Configuration=Release /p:AdditionalIncludePaths=./:ocesql win/ocesql.sln
    
    - name: Version display
      working-directory: win
      run: |
        ./install.ps1
        $env:PATH=";C:\ocesql4j\bin"
        $env:CLASSPATH="C:\ocesql4j\ocesql4j.jar;"
        ocesql --version

    - name: Test SQL connection
      working-directory: sample
      run: |
        copy ../copy/sqlca.cbl .
        ocesql FETCHTBL.cbl  FETCHTBL.cob
        ocesql INSERTTBL.cbl INSERTTBL.cob
        cobj INSERTTBL.cob
        cobj FETCHTBL.cob
        java INSERTTBL
        java FETCHTBL